name: Sync to Hugging Face Spaces

on:
  push:
    branches: [deployment_readiness, main]
    paths:
      - 'python-extractor/**'
      - '.github/workflows/hf-sync.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Update these to match your Space
          HF_USERNAME: pmitra96
          HF_SPACE_NAME: pateproject
        run: |
          git config --global user.email "pmitra96@gmail.com"
          git config --global user.name "pmitra96"
          
          # Add Hugging Face Space as a remote
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME
          
          # Push the python-extractor subdirectory to the root of the HF Space
          git push hf `git subtree split --prefix=python-extractor HEAD`:main --force
